### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by dpo** [ooJerryLeeoo/hyper-material-box#2]
After following the instructions and reloading, the terminal hangs and I see the following error message in the developer tools:
```
Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cannot read property 'blue' of undefined
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cannot read property 'blue' of undefined
    at callFunction (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/rpc-server.js:235:11)
    at EventEmitter.<anonymous> (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/rpc-server.js:342:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```
If I quit Hyper and restart, it never comes up. I'm using Hyper 1.3.3.1754 on macOS 10.12.5.

**Comment by dpo** [comment]
Apologies. My fault.
